# Generated by Django 5.0.3 on 2024-03-10 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_book_updated_date_alter_borrow_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='updated_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 10, 19, 34, 1, 228832)),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='updated_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 10, 19, 34, 1, 228832)),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='updated_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 10, 19, 34, 1, 227826)),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 10, 19, 34, 1, 226820)),
        ),
    ]
