# Generated by Django 5.0.3 on 2024-03-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_book_updated_date_alter_borrow_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
